version: 0.2
phases:
  install:
    commands:
    - npm install time
    - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-us-west-2-431996776868
      --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
  - samTemplate.yaml
  - outputSamTemplate.yaml
