AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the category
Resources:
  SaveSurveyResult:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/api/SaveSurveyResult.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          SURVEY_TABLE: !Ref SurveyTable
      Events:
        MyCategoryApi:
          Type: Api
          Properties:
            Path: /SaveSurveyResult
            Method: POST

  SurveyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5